#!/usr/bin/env python3
"""Generate the dense GBK two-byte to Unicode BMP lookup table."""

from pathlib import Path


OUTPUT = Path(__file__).resolve().parents[1] / "lib" / "Txt" / "GbkToUnicodeTable.inc"


def mapped_codepoint(lead: int, trail: int) -> int:
    try:
        text = bytes((lead, trail)).decode("gbk")
    except UnicodeDecodeError:
        return 0
    if len(text) != 1 or ord(text) > 0xFFFF:
        return 0
    return ord(text)


def main() -> None:
    trails = (*range(0x40, 0x7F), *range(0x80, 0xFF))
    values = [mapped_codepoint(lead, trail) for lead in range(0x81, 0xFF) for trail in trails]
    lines = [
        "// Generated by scripts/generate_gbk_table.py from Python's standard GBK codec.",
        "// Do not edit manually.",
        "static constexpr uint16_t kGbkToUnicode[] = {",
    ]
    for start in range(0, len(values), 12):
        lines.append("    " + ", ".join(f"0x{value:04X}" for value in values[start : start + 12]) + ",")
    lines.extend(("};", "static_assert(sizeof(kGbkToUnicode) / sizeof(kGbkToUnicode[0]) == 126 * 190);", ""))
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
